/*     */ package org.apache.pdfbox.encoding;
/*     */ 
/*     */ import java.util.Map;
/*     */ import org.apache.pdfbox.cos.COSBase;
/*     */ import org.apache.pdfbox.cos.COSName;
/*     */ 
/*     */ public class MacRomanEncoding extends Encoding
/*     */ {
/*  35 */   public static final MacRomanEncoding INSTANCE = new MacRomanEncoding();
/*     */ 
/*     */   public MacRomanEncoding()
/*     */   {
/*  42 */     addCharacterEncoding(65, "A");
/*  43 */     addCharacterEncoding(174, "AE");
/*  44 */     addCharacterEncoding(231, "Aacute");
/*  45 */     addCharacterEncoding(229, "Acircumflex");
/*  46 */     addCharacterEncoding(128, "Adieresis");
/*  47 */     addCharacterEncoding(203, "Agrave");
/*  48 */     addCharacterEncoding(129, "Aring");
/*  49 */     addCharacterEncoding(204, "Atilde");
/*  50 */     addCharacterEncoding(66, "B");
/*  51 */     addCharacterEncoding(67, "C");
/*  52 */     addCharacterEncoding(130, "Ccedilla");
/*  53 */     addCharacterEncoding(68, "D");
/*  54 */     addCharacterEncoding(69, "E");
/*  55 */     addCharacterEncoding(131, "Eacute");
/*  56 */     addCharacterEncoding(230, "Ecircumflex");
/*  57 */     addCharacterEncoding(232, "Edieresis");
/*  58 */     addCharacterEncoding(233, "Egrave");
/*  59 */     addCharacterEncoding(70, "F");
/*  60 */     addCharacterEncoding(71, "G");
/*  61 */     addCharacterEncoding(72, "H");
/*  62 */     addCharacterEncoding(73, "I");
/*  63 */     addCharacterEncoding(234, "Iacute");
/*  64 */     addCharacterEncoding(235, "Icircumflex");
/*  65 */     addCharacterEncoding(236, "Idieresis");
/*  66 */     addCharacterEncoding(237, "Igrave");
/*  67 */     addCharacterEncoding(74, "J");
/*  68 */     addCharacterEncoding(75, "K");
/*  69 */     addCharacterEncoding(76, "L");
/*  70 */     addCharacterEncoding(77, "M");
/*  71 */     addCharacterEncoding(78, "N");
/*  72 */     addCharacterEncoding(132, "Ntilde");
/*  73 */     addCharacterEncoding(79, "O");
/*  74 */     addCharacterEncoding(206, "OE");
/*  75 */     addCharacterEncoding(238, "Oacute");
/*  76 */     addCharacterEncoding(239, "Ocircumflex");
/*  77 */     addCharacterEncoding(133, "Odieresis");
/*  78 */     addCharacterEncoding(241, "Ograve");
/*  79 */     addCharacterEncoding(175, "Oslash");
/*  80 */     addCharacterEncoding(205, "Otilde");
/*  81 */     addCharacterEncoding(80, "P");
/*  82 */     addCharacterEncoding(81, "Q");
/*  83 */     addCharacterEncoding(82, "R");
/*  84 */     addCharacterEncoding(83, "S");
/*  85 */     addCharacterEncoding(84, "T");
/*  86 */     addCharacterEncoding(85, "U");
/*  87 */     addCharacterEncoding(242, "Uacute");
/*  88 */     addCharacterEncoding(243, "Ucircumflex");
/*  89 */     addCharacterEncoding(134, "Udieresis");
/*  90 */     addCharacterEncoding(244, "Ugrave");
/*  91 */     addCharacterEncoding(86, "V");
/*  92 */     addCharacterEncoding(87, "W");
/*  93 */     addCharacterEncoding(88, "X");
/*  94 */     addCharacterEncoding(89, "Y");
/*  95 */     addCharacterEncoding(217, "Ydieresis");
/*  96 */     addCharacterEncoding(90, "Z");
/*  97 */     addCharacterEncoding(97, "a");
/*  98 */     addCharacterEncoding(135, "aacute");
/*  99 */     addCharacterEncoding(137, "acircumflex");
/* 100 */     addCharacterEncoding(171, "acute");
/* 101 */     addCharacterEncoding(138, "adieresis");
/* 102 */     addCharacterEncoding(190, "ae");
/* 103 */     addCharacterEncoding(136, "agrave");
/* 104 */     addCharacterEncoding(38, "ampersand");
/* 105 */     addCharacterEncoding(140, "aring");
/* 106 */     addCharacterEncoding(94, "asciicircum");
/* 107 */     addCharacterEncoding(126, "asciitilde");
/* 108 */     addCharacterEncoding(42, "asterisk");
/* 109 */     addCharacterEncoding(64, "at");
/* 110 */     addCharacterEncoding(139, "atilde");
/* 111 */     addCharacterEncoding(98, "b");
/* 112 */     addCharacterEncoding(92, "backslash");
/* 113 */     addCharacterEncoding(124, "bar");
/* 114 */     addCharacterEncoding(123, "braceleft");
/* 115 */     addCharacterEncoding(125, "braceright");
/* 116 */     addCharacterEncoding(91, "bracketleft");
/* 117 */     addCharacterEncoding(93, "bracketright");
/* 118 */     addCharacterEncoding(249, "breve");
/* 119 */     addCharacterEncoding(165, "bullet");
/* 120 */     addCharacterEncoding(99, "c");
/* 121 */     addCharacterEncoding(255, "caron");
/* 122 */     addCharacterEncoding(141, "ccedilla");
/* 123 */     addCharacterEncoding(252, "cedilla");
/* 124 */     addCharacterEncoding(162, "cent");
/* 125 */     addCharacterEncoding(246, "circumflex");
/* 126 */     addCharacterEncoding(58, "colon");
/* 127 */     addCharacterEncoding(44, "comma");
/* 128 */     addCharacterEncoding(169, "copyright");
/* 129 */     addCharacterEncoding(219, "currency");
/* 130 */     addCharacterEncoding(100, "d");
/* 131 */     addCharacterEncoding(160, "dagger");
/* 132 */     addCharacterEncoding(224, "daggerdbl");
/* 133 */     addCharacterEncoding(161, "degree");
/* 134 */     addCharacterEncoding(172, "dieresis");
/* 135 */     addCharacterEncoding(214, "divide");
/* 136 */     addCharacterEncoding(36, "dollar");
/* 137 */     addCharacterEncoding(250, "dotaccent");
/* 138 */     addCharacterEncoding(245, "dotlessi");
/* 139 */     addCharacterEncoding(101, "e");
/* 140 */     addCharacterEncoding(142, "eacute");
/* 141 */     addCharacterEncoding(144, "ecircumflex");
/* 142 */     addCharacterEncoding(145, "edieresis");
/* 143 */     addCharacterEncoding(143, "egrave");
/* 144 */     addCharacterEncoding(56, "eight");
/* 145 */     addCharacterEncoding(201, "ellipsis");
/* 146 */     addCharacterEncoding(209, "emdash");
/* 147 */     addCharacterEncoding(208, "endash");
/* 148 */     addCharacterEncoding(61, "equal");
/* 149 */     addCharacterEncoding(33, "exclam");
/* 150 */     addCharacterEncoding(193, "exclamdown");
/* 151 */     addCharacterEncoding(102, "f");
/* 152 */     addCharacterEncoding(222, "fi");
/* 153 */     addCharacterEncoding(53, "five");
/* 154 */     addCharacterEncoding(223, "fl");
/* 155 */     addCharacterEncoding(196, "florin");
/* 156 */     addCharacterEncoding(52, "four");
/* 157 */     addCharacterEncoding(218, "fraction");
/* 158 */     addCharacterEncoding(103, "g");
/* 159 */     addCharacterEncoding(167, "germandbls");
/* 160 */     addCharacterEncoding(96, "grave");
/* 161 */     addCharacterEncoding(62, "greater");
/* 162 */     addCharacterEncoding(199, "guillemotleft");
/* 163 */     addCharacterEncoding(200, "guillemotright");
/* 164 */     addCharacterEncoding(220, "guilsinglleft");
/* 165 */     addCharacterEncoding(221, "guilsinglright");
/* 166 */     addCharacterEncoding(104, "h");
/* 167 */     addCharacterEncoding(253, "hungarumlaut");
/* 168 */     addCharacterEncoding(45, "hyphen");
/* 169 */     addCharacterEncoding(105, "i");
/* 170 */     addCharacterEncoding(146, "iacute");
/* 171 */     addCharacterEncoding(148, "icircumflex");
/* 172 */     addCharacterEncoding(149, "idieresis");
/* 173 */     addCharacterEncoding(147, "igrave");
/* 174 */     addCharacterEncoding(106, "j");
/* 175 */     addCharacterEncoding(107, "k");
/* 176 */     addCharacterEncoding(108, "l");
/* 177 */     addCharacterEncoding(60, "less");
/* 178 */     addCharacterEncoding(194, "logicalnot");
/* 179 */     addCharacterEncoding(109, "m");
/* 180 */     addCharacterEncoding(248, "macron");
/* 181 */     addCharacterEncoding(181, "mu");
/* 182 */     addCharacterEncoding(110, "n");
/* 183 */     addCharacterEncoding(57, "nine");
/* 184 */     addCharacterEncoding(150, "ntilde");
/* 185 */     addCharacterEncoding(35, "numbersign");
/* 186 */     addCharacterEncoding(111, "o");
/* 187 */     addCharacterEncoding(151, "oacute");
/* 188 */     addCharacterEncoding(153, "ocircumflex");
/* 189 */     addCharacterEncoding(154, "odieresis");
/* 190 */     addCharacterEncoding(207, "oe");
/* 191 */     addCharacterEncoding(254, "ogonek");
/* 192 */     addCharacterEncoding(152, "ograve");
/* 193 */     addCharacterEncoding(49, "one");
/* 194 */     addCharacterEncoding(187, "ordfeminine");
/* 195 */     addCharacterEncoding(188, "ordmasculine");
/* 196 */     addCharacterEncoding(191, "oslash");
/* 197 */     addCharacterEncoding(155, "otilde");
/* 198 */     addCharacterEncoding(112, "p");
/* 199 */     addCharacterEncoding(166, "paragraph");
/* 200 */     addCharacterEncoding(40, "parenleft");
/* 201 */     addCharacterEncoding(41, "parenright");
/* 202 */     addCharacterEncoding(37, "percent");
/* 203 */     addCharacterEncoding(46, "period");
/* 204 */     addCharacterEncoding(225, "periodcentered");
/* 205 */     addCharacterEncoding(228, "perthousand");
/* 206 */     addCharacterEncoding(43, "plus");
/* 207 */     addCharacterEncoding(177, "plusminus");
/* 208 */     addCharacterEncoding(113, "q");
/* 209 */     addCharacterEncoding(63, "question");
/* 210 */     addCharacterEncoding(192, "questiondown");
/* 211 */     addCharacterEncoding(34, "quotedbl");
/* 212 */     addCharacterEncoding(227, "quotedblbase");
/* 213 */     addCharacterEncoding(210, "quotedblleft");
/* 214 */     addCharacterEncoding(211, "quotedblright");
/* 215 */     addCharacterEncoding(212, "quoteleft");
/* 216 */     addCharacterEncoding(213, "quoteright");
/* 217 */     addCharacterEncoding(226, "quotesinglbase");
/* 218 */     addCharacterEncoding(39, "quotesingle");
/* 219 */     addCharacterEncoding(114, "r");
/* 220 */     addCharacterEncoding(168, "registered");
/* 221 */     addCharacterEncoding(251, "ring");
/* 222 */     addCharacterEncoding(115, "s");
/* 223 */     addCharacterEncoding(164, "section");
/* 224 */     addCharacterEncoding(59, "semicolon");
/* 225 */     addCharacterEncoding(55, "seven");
/* 226 */     addCharacterEncoding(54, "six");
/* 227 */     addCharacterEncoding(47, "slash");
/* 228 */     addCharacterEncoding(32, "space");
/* 229 */     addCharacterEncoding(163, "sterling");
/* 230 */     addCharacterEncoding(116, "t");
/* 231 */     addCharacterEncoding(51, "three");
/* 232 */     addCharacterEncoding(247, "tilde");
/* 233 */     addCharacterEncoding(170, "trademark");
/* 234 */     addCharacterEncoding(50, "two");
/* 235 */     addCharacterEncoding(117, "u");
/* 236 */     addCharacterEncoding(156, "uacute");
/* 237 */     addCharacterEncoding(158, "ucircumflex");
/* 238 */     addCharacterEncoding(159, "udieresis");
/* 239 */     addCharacterEncoding(157, "ugrave");
/* 240 */     addCharacterEncoding(95, "underscore");
/* 241 */     addCharacterEncoding(118, "v");
/* 242 */     addCharacterEncoding(119, "w");
/* 243 */     addCharacterEncoding(120, "x");
/* 244 */     addCharacterEncoding(121, "y");
/* 245 */     addCharacterEncoding(216, "ydieresis");
/* 246 */     addCharacterEncoding(180, "yen");
/* 247 */     addCharacterEncoding(122, "z");
/* 248 */     addCharacterEncoding(48, "zero");
/*     */ 
/* 252 */     this.codeToName.put(Integer.valueOf(202), "space");
/*     */   }
/*     */ 
/*     */   public COSBase getCOSObject()
/*     */   {
/* 262 */     return COSName.MAC_ROMAN_ENCODING;
/*     */   }
/*     */ }

/* Location:           C:\Users\ESa10969\Desktop\PDFComparer\
 * Qualified Name:     org.apache.pdfbox.encoding.MacRomanEncoding
 * JD-Core Version:    0.6.2
 */