/*     */ package com.itextpdf.text.xml.simpleparser;
/*     */ 
/*     */ import com.itextpdf.text.Chunk;
/*     */ import com.itextpdf.text.Font;
/*     */ import com.itextpdf.text.Font.FontFamily;
/*     */ import java.util.HashMap;
/*     */ import java.util.Map;
/*     */ 
/*     */ public class EntitiesToSymbol
/*     */ {
/*  67 */   private static final Map<String, Character> MAP = new HashMap();
/*     */ 
/*     */   public static Chunk get(String e, Font font)
/*     */   {
/* 351 */     char s = getCorrespondingSymbol(e);
/* 352 */     if (s == 0) {
/*     */       try {
/* 354 */         return new Chunk(String.valueOf((char)Integer.parseInt(e)), font);
/*     */       }
/*     */       catch (Exception exception) {
/* 357 */         return new Chunk(e, font);
/*     */       }
/*     */     }
/* 360 */     Font symbol = new Font(Font.FontFamily.SYMBOL, font.getSize(), font.getStyle(), font.getColor());
/* 361 */     return new Chunk(String.valueOf(s), symbol);
/*     */   }
/*     */ 
/*     */   public static char getCorrespondingSymbol(String name)
/*     */   {
/* 371 */     Character symbol = (Character)MAP.get(name);
/* 372 */     if (symbol == null) {
/* 373 */       return '\000';
/*     */     }
/* 375 */     return symbol.charValue();
/*     */   }
/*     */ 
/*     */   static
/*     */   {
/*  68 */     MAP.put("169", Character.valueOf('ã'));
/*  69 */     MAP.put("172", Character.valueOf('Ø'));
/*  70 */     MAP.put("174", Character.valueOf('Ò'));
/*  71 */     MAP.put("177", Character.valueOf('±'));
/*  72 */     MAP.put("215", Character.valueOf('´'));
/*  73 */     MAP.put("247", Character.valueOf('¸'));
/*  74 */     MAP.put("8230", Character.valueOf('¼'));
/*  75 */     MAP.put("8242", Character.valueOf('¢'));
/*  76 */     MAP.put("8243", Character.valueOf('²'));
/*  77 */     MAP.put("8260", Character.valueOf('¤'));
/*  78 */     MAP.put("8364", Character.valueOf('ð'));
/*  79 */     MAP.put("8465", Character.valueOf('Á'));
/*  80 */     MAP.put("8472", Character.valueOf('Ã'));
/*  81 */     MAP.put("8476", Character.valueOf('Â'));
/*  82 */     MAP.put("8482", Character.valueOf('Ô'));
/*  83 */     MAP.put("8501", Character.valueOf('À'));
/*  84 */     MAP.put("8592", Character.valueOf('¬'));
/*  85 */     MAP.put("8593", Character.valueOf('­'));
/*  86 */     MAP.put("8594", Character.valueOf('®'));
/*  87 */     MAP.put("8595", Character.valueOf('¯'));
/*  88 */     MAP.put("8596", Character.valueOf('«'));
/*  89 */     MAP.put("8629", Character.valueOf('¿'));
/*  90 */     MAP.put("8656", Character.valueOf('Ü'));
/*  91 */     MAP.put("8657", Character.valueOf('Ý'));
/*  92 */     MAP.put("8658", Character.valueOf('Þ'));
/*  93 */     MAP.put("8659", Character.valueOf('ß'));
/*  94 */     MAP.put("8660", Character.valueOf('Û'));
/*  95 */     MAP.put("8704", Character.valueOf('"'));
/*  96 */     MAP.put("8706", Character.valueOf('¶'));
/*  97 */     MAP.put("8707", Character.valueOf('$'));
/*  98 */     MAP.put("8709", Character.valueOf('Æ'));
/*  99 */     MAP.put("8711", Character.valueOf('Ñ'));
/* 100 */     MAP.put("8712", Character.valueOf('Î'));
/* 101 */     MAP.put("8713", Character.valueOf('Ï'));
/* 102 */     MAP.put("8717", Character.valueOf('\''));
/* 103 */     MAP.put("8719", Character.valueOf('Õ'));
/* 104 */     MAP.put("8721", Character.valueOf('å'));
/* 105 */     MAP.put("8722", Character.valueOf('-'));
/* 106 */     MAP.put("8727", Character.valueOf('*'));
/* 107 */     MAP.put("8729", Character.valueOf('·'));
/* 108 */     MAP.put("8730", Character.valueOf('Ö'));
/* 109 */     MAP.put("8733", Character.valueOf('µ'));
/* 110 */     MAP.put("8734", Character.valueOf('¥'));
/* 111 */     MAP.put("8736", Character.valueOf('Ð'));
/* 112 */     MAP.put("8743", Character.valueOf('Ù'));
/* 113 */     MAP.put("8744", Character.valueOf('Ú'));
/* 114 */     MAP.put("8745", Character.valueOf('Ç'));
/* 115 */     MAP.put("8746", Character.valueOf('È'));
/* 116 */     MAP.put("8747", Character.valueOf('ò'));
/* 117 */     MAP.put("8756", Character.valueOf('\\'));
/* 118 */     MAP.put("8764", Character.valueOf('~'));
/* 119 */     MAP.put("8773", Character.valueOf('@'));
/* 120 */     MAP.put("8776", Character.valueOf('»'));
/* 121 */     MAP.put("8800", Character.valueOf('¹'));
/* 122 */     MAP.put("8801", Character.valueOf('º'));
/* 123 */     MAP.put("8804", Character.valueOf('£'));
/* 124 */     MAP.put("8805", Character.valueOf('³'));
/* 125 */     MAP.put("8834", Character.valueOf('Ì'));
/* 126 */     MAP.put("8835", Character.valueOf('É'));
/* 127 */     MAP.put("8836", Character.valueOf('Ë'));
/* 128 */     MAP.put("8838", Character.valueOf('Í'));
/* 129 */     MAP.put("8839", Character.valueOf('Ê'));
/* 130 */     MAP.put("8853", Character.valueOf('Å'));
/* 131 */     MAP.put("8855", Character.valueOf('Ä'));
/* 132 */     MAP.put("8869", Character.valueOf('^'));
/* 133 */     MAP.put("8901", Character.valueOf('×'));
/* 134 */     MAP.put("8992", Character.valueOf('ó'));
/* 135 */     MAP.put("8993", Character.valueOf('õ'));
/* 136 */     MAP.put("9001", Character.valueOf('á'));
/* 137 */     MAP.put("9002", Character.valueOf('ñ'));
/* 138 */     MAP.put("913", Character.valueOf('A'));
/* 139 */     MAP.put("914", Character.valueOf('B'));
/* 140 */     MAP.put("915", Character.valueOf('G'));
/* 141 */     MAP.put("916", Character.valueOf('D'));
/* 142 */     MAP.put("917", Character.valueOf('E'));
/* 143 */     MAP.put("918", Character.valueOf('Z'));
/* 144 */     MAP.put("919", Character.valueOf('H'));
/* 145 */     MAP.put("920", Character.valueOf('Q'));
/* 146 */     MAP.put("921", Character.valueOf('I'));
/* 147 */     MAP.put("922", Character.valueOf('K'));
/* 148 */     MAP.put("923", Character.valueOf('L'));
/* 149 */     MAP.put("924", Character.valueOf('M'));
/* 150 */     MAP.put("925", Character.valueOf('N'));
/* 151 */     MAP.put("926", Character.valueOf('X'));
/* 152 */     MAP.put("927", Character.valueOf('O'));
/* 153 */     MAP.put("928", Character.valueOf('P'));
/* 154 */     MAP.put("929", Character.valueOf('R'));
/* 155 */     MAP.put("931", Character.valueOf('S'));
/* 156 */     MAP.put("932", Character.valueOf('T'));
/* 157 */     MAP.put("933", Character.valueOf('U'));
/* 158 */     MAP.put("934", Character.valueOf('F'));
/* 159 */     MAP.put("935", Character.valueOf('C'));
/* 160 */     MAP.put("936", Character.valueOf('Y'));
/* 161 */     MAP.put("937", Character.valueOf('W'));
/* 162 */     MAP.put("945", Character.valueOf('a'));
/* 163 */     MAP.put("946", Character.valueOf('b'));
/* 164 */     MAP.put("947", Character.valueOf('g'));
/* 165 */     MAP.put("948", Character.valueOf('d'));
/* 166 */     MAP.put("949", Character.valueOf('e'));
/* 167 */     MAP.put("950", Character.valueOf('z'));
/* 168 */     MAP.put("951", Character.valueOf('h'));
/* 169 */     MAP.put("952", Character.valueOf('q'));
/* 170 */     MAP.put("953", Character.valueOf('i'));
/* 171 */     MAP.put("954", Character.valueOf('k'));
/* 172 */     MAP.put("955", Character.valueOf('l'));
/* 173 */     MAP.put("956", Character.valueOf('m'));
/* 174 */     MAP.put("957", Character.valueOf('n'));
/* 175 */     MAP.put("958", Character.valueOf('x'));
/* 176 */     MAP.put("959", Character.valueOf('o'));
/* 177 */     MAP.put("960", Character.valueOf('p'));
/* 178 */     MAP.put("961", Character.valueOf('r'));
/* 179 */     MAP.put("962", Character.valueOf('V'));
/* 180 */     MAP.put("963", Character.valueOf('s'));
/* 181 */     MAP.put("964", Character.valueOf('t'));
/* 182 */     MAP.put("965", Character.valueOf('u'));
/* 183 */     MAP.put("966", Character.valueOf('f'));
/* 184 */     MAP.put("967", Character.valueOf('c'));
/* 185 */     MAP.put("9674", Character.valueOf('à'));
/* 186 */     MAP.put("968", Character.valueOf('y'));
/* 187 */     MAP.put("969", Character.valueOf('w'));
/* 188 */     MAP.put("977", Character.valueOf('J'));
/* 189 */     MAP.put("978", Character.valueOf('¡'));
/* 190 */     MAP.put("981", Character.valueOf('j'));
/* 191 */     MAP.put("982", Character.valueOf('v'));
/* 192 */     MAP.put("9824", Character.valueOf('ª'));
/* 193 */     MAP.put("9827", Character.valueOf('§'));
/* 194 */     MAP.put("9829", Character.valueOf('©'));
/* 195 */     MAP.put("9830", Character.valueOf('¨'));
/* 196 */     MAP.put("Alpha", Character.valueOf('A'));
/* 197 */     MAP.put("Beta", Character.valueOf('B'));
/* 198 */     MAP.put("Chi", Character.valueOf('C'));
/* 199 */     MAP.put("Delta", Character.valueOf('D'));
/* 200 */     MAP.put("Epsilon", Character.valueOf('E'));
/* 201 */     MAP.put("Eta", Character.valueOf('H'));
/* 202 */     MAP.put("Gamma", Character.valueOf('G'));
/* 203 */     MAP.put("Iota", Character.valueOf('I'));
/* 204 */     MAP.put("Kappa", Character.valueOf('K'));
/* 205 */     MAP.put("Lambda", Character.valueOf('L'));
/* 206 */     MAP.put("Mu", Character.valueOf('M'));
/* 207 */     MAP.put("Nu", Character.valueOf('N'));
/* 208 */     MAP.put("Omega", Character.valueOf('W'));
/* 209 */     MAP.put("Omicron", Character.valueOf('O'));
/* 210 */     MAP.put("Phi", Character.valueOf('F'));
/* 211 */     MAP.put("Pi", Character.valueOf('P'));
/* 212 */     MAP.put("Prime", Character.valueOf('²'));
/* 213 */     MAP.put("Psi", Character.valueOf('Y'));
/* 214 */     MAP.put("Rho", Character.valueOf('R'));
/* 215 */     MAP.put("Sigma", Character.valueOf('S'));
/* 216 */     MAP.put("Tau", Character.valueOf('T'));
/* 217 */     MAP.put("Theta", Character.valueOf('Q'));
/* 218 */     MAP.put("Upsilon", Character.valueOf('U'));
/* 219 */     MAP.put("Xi", Character.valueOf('X'));
/* 220 */     MAP.put("Zeta", Character.valueOf('Z'));
/* 221 */     MAP.put("alefsym", Character.valueOf('À'));
/* 222 */     MAP.put("alpha", Character.valueOf('a'));
/* 223 */     MAP.put("and", Character.valueOf('Ù'));
/* 224 */     MAP.put("ang", Character.valueOf('Ð'));
/* 225 */     MAP.put("asymp", Character.valueOf('»'));
/* 226 */     MAP.put("beta", Character.valueOf('b'));
/* 227 */     MAP.put("cap", Character.valueOf('Ç'));
/* 228 */     MAP.put("chi", Character.valueOf('c'));
/* 229 */     MAP.put("clubs", Character.valueOf('§'));
/* 230 */     MAP.put("cong", Character.valueOf('@'));
/* 231 */     MAP.put("copy", Character.valueOf('Ó'));
/* 232 */     MAP.put("crarr", Character.valueOf('¿'));
/* 233 */     MAP.put("cup", Character.valueOf('È'));
/* 234 */     MAP.put("dArr", Character.valueOf('ß'));
/* 235 */     MAP.put("darr", Character.valueOf('¯'));
/* 236 */     MAP.put("delta", Character.valueOf('d'));
/* 237 */     MAP.put("diams", Character.valueOf('¨'));
/* 238 */     MAP.put("divide", Character.valueOf('¸'));
/* 239 */     MAP.put("empty", Character.valueOf('Æ'));
/* 240 */     MAP.put("epsilon", Character.valueOf('e'));
/* 241 */     MAP.put("equiv", Character.valueOf('º'));
/* 242 */     MAP.put("eta", Character.valueOf('h'));
/* 243 */     MAP.put("euro", Character.valueOf('ð'));
/* 244 */     MAP.put("exist", Character.valueOf('$'));
/* 245 */     MAP.put("forall", Character.valueOf('"'));
/* 246 */     MAP.put("frasl", Character.valueOf('¤'));
/* 247 */     MAP.put("gamma", Character.valueOf('g'));
/* 248 */     MAP.put("ge", Character.valueOf('³'));
/* 249 */     MAP.put("hArr", Character.valueOf('Û'));
/* 250 */     MAP.put("harr", Character.valueOf('«'));
/* 251 */     MAP.put("hearts", Character.valueOf('©'));
/* 252 */     MAP.put("hellip", Character.valueOf('¼'));
/* 253 */     MAP.put("horizontal arrow extender", Character.valueOf('¾'));
/* 254 */     MAP.put("image", Character.valueOf('Á'));
/* 255 */     MAP.put("infin", Character.valueOf('¥'));
/* 256 */     MAP.put("int", Character.valueOf('ò'));
/* 257 */     MAP.put("iota", Character.valueOf('i'));
/* 258 */     MAP.put("isin", Character.valueOf('Î'));
/* 259 */     MAP.put("kappa", Character.valueOf('k'));
/* 260 */     MAP.put("lArr", Character.valueOf('Ü'));
/* 261 */     MAP.put("lambda", Character.valueOf('l'));
/* 262 */     MAP.put("lang", Character.valueOf('á'));
/* 263 */     MAP.put("large brace extender", Character.valueOf('ï'));
/* 264 */     MAP.put("large integral extender", Character.valueOf('ô'));
/* 265 */     MAP.put("large left brace (bottom)", Character.valueOf('î'));
/* 266 */     MAP.put("large left brace (middle)", Character.valueOf('í'));
/* 267 */     MAP.put("large left brace (top)", Character.valueOf('ì'));
/* 268 */     MAP.put("large left bracket (bottom)", Character.valueOf('ë'));
/* 269 */     MAP.put("large left bracket (extender)", Character.valueOf('ê'));
/* 270 */     MAP.put("large left bracket (top)", Character.valueOf('é'));
/* 271 */     MAP.put("large left parenthesis (bottom)", Character.valueOf('è'));
/* 272 */     MAP.put("large left parenthesis (extender)", Character.valueOf('ç'));
/* 273 */     MAP.put("large left parenthesis (top)", Character.valueOf('æ'));
/* 274 */     MAP.put("large right brace (bottom)", Character.valueOf('þ'));
/* 275 */     MAP.put("large right brace (middle)", Character.valueOf('ý'));
/* 276 */     MAP.put("large right brace (top)", Character.valueOf('ü'));
/* 277 */     MAP.put("large right bracket (bottom)", Character.valueOf('û'));
/* 278 */     MAP.put("large right bracket (extender)", Character.valueOf('ú'));
/* 279 */     MAP.put("large right bracket (top)", Character.valueOf('ù'));
/* 280 */     MAP.put("large right parenthesis (bottom)", Character.valueOf('ø'));
/* 281 */     MAP.put("large right parenthesis (extender)", Character.valueOf('÷'));
/* 282 */     MAP.put("large right parenthesis (top)", Character.valueOf('ö'));
/* 283 */     MAP.put("larr", Character.valueOf('¬'));
/* 284 */     MAP.put("le", Character.valueOf('£'));
/* 285 */     MAP.put("lowast", Character.valueOf('*'));
/* 286 */     MAP.put("loz", Character.valueOf('à'));
/* 287 */     MAP.put("minus", Character.valueOf('-'));
/* 288 */     MAP.put("mu", Character.valueOf('m'));
/* 289 */     MAP.put("nabla", Character.valueOf('Ñ'));
/* 290 */     MAP.put("ne", Character.valueOf('¹'));
/* 291 */     MAP.put("not", Character.valueOf('Ø'));
/* 292 */     MAP.put("notin", Character.valueOf('Ï'));
/* 293 */     MAP.put("nsub", Character.valueOf('Ë'));
/* 294 */     MAP.put("nu", Character.valueOf('n'));
/* 295 */     MAP.put("omega", Character.valueOf('w'));
/* 296 */     MAP.put("omicron", Character.valueOf('o'));
/* 297 */     MAP.put("oplus", Character.valueOf('Å'));
/* 298 */     MAP.put("or", Character.valueOf('Ú'));
/* 299 */     MAP.put("otimes", Character.valueOf('Ä'));
/* 300 */     MAP.put("part", Character.valueOf('¶'));
/* 301 */     MAP.put("perp", Character.valueOf('^'));
/* 302 */     MAP.put("phi", Character.valueOf('f'));
/* 303 */     MAP.put("pi", Character.valueOf('p'));
/* 304 */     MAP.put("piv", Character.valueOf('v'));
/* 305 */     MAP.put("plusmn", Character.valueOf('±'));
/* 306 */     MAP.put("prime", Character.valueOf('¢'));
/* 307 */     MAP.put("prod", Character.valueOf('Õ'));
/* 308 */     MAP.put("prop", Character.valueOf('µ'));
/* 309 */     MAP.put("psi", Character.valueOf('y'));
/* 310 */     MAP.put("rArr", Character.valueOf('Þ'));
/* 311 */     MAP.put("radic", Character.valueOf('Ö'));
/* 312 */     MAP.put("radical extender", Character.valueOf('`'));
/* 313 */     MAP.put("rang", Character.valueOf('ñ'));
/* 314 */     MAP.put("rarr", Character.valueOf('®'));
/* 315 */     MAP.put("real", Character.valueOf('Â'));
/* 316 */     MAP.put("reg", Character.valueOf('Ò'));
/* 317 */     MAP.put("rho", Character.valueOf('r'));
/* 318 */     MAP.put("sdot", Character.valueOf('×'));
/* 319 */     MAP.put("sigma", Character.valueOf('s'));
/* 320 */     MAP.put("sigmaf", Character.valueOf('V'));
/* 321 */     MAP.put("sim", Character.valueOf('~'));
/* 322 */     MAP.put("spades", Character.valueOf('ª'));
/* 323 */     MAP.put("sub", Character.valueOf('Ì'));
/* 324 */     MAP.put("sube", Character.valueOf('Í'));
/* 325 */     MAP.put("sum", Character.valueOf('å'));
/* 326 */     MAP.put("sup", Character.valueOf('É'));
/* 327 */     MAP.put("supe", Character.valueOf('Ê'));
/* 328 */     MAP.put("tau", Character.valueOf('t'));
/* 329 */     MAP.put("there4", Character.valueOf('\\'));
/* 330 */     MAP.put("theta", Character.valueOf('q'));
/* 331 */     MAP.put("thetasym", Character.valueOf('J'));
/* 332 */     MAP.put("times", Character.valueOf('´'));
/* 333 */     MAP.put("trade", Character.valueOf('Ô'));
/* 334 */     MAP.put("uArr", Character.valueOf('Ý'));
/* 335 */     MAP.put("uarr", Character.valueOf('­'));
/* 336 */     MAP.put("upsih", Character.valueOf('¡'));
/* 337 */     MAP.put("upsilon", Character.valueOf('u'));
/* 338 */     MAP.put("vertical arrow extender", Character.valueOf('½'));
/* 339 */     MAP.put("weierp", Character.valueOf('Ã'));
/* 340 */     MAP.put("xi", Character.valueOf('x'));
/* 341 */     MAP.put("zeta", Character.valueOf('z'));
/*     */   }
/*     */ }

/* Location:           C:\Users\ESa10969\Desktop\PDFComparer\
 * Qualified Name:     com.itextpdf.text.xml.simpleparser.EntitiesToSymbol
 * JD-Core Version:    0.6.2
 */